# Generated by Django 5.0.6 on 2024-05-22 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
            ],
        ),
        migrations.CreateModel(
            name='DayNightshift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifttype', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Day-OT', 'Day-OT'), ('Night-OT', 'Night-OT')], max_length=50, verbose_name='Shift Details')),
            ],
        ),
        migrations.CreateModel(
            name='oilcategorydetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('oilcategoryname', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.branddetails')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingRollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_no', models.CharField(max_length=100)),
                ('operator_name', models.CharField(max_length=100)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.daynightshift')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingRollDetail',
            fields=[
                ('filmrollno', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Film Roll No')),
                ('filmrolldate', models.DateField(verbose_name='Film Roll Date')),
                ('grosswt', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gross Weight')),
                ('netwt', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Net Weight')),
                ('printingrollbatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.printingrollbatch')),
            ],
        ),
        migrations.CreateModel(
            name='skunamedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuname', models.CharField(max_length=50, verbose_name='SKU Name')),
                ('skucode', models.CharField(max_length=50, unique=True, verbose_name='SKU Code')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('catgorty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.oilcategorydetails')),
            ],
        ),
        migrations.AddField(
            model_name='printingrollbatch',
            name='skuname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.skunamedetails'),
        ),
    ]
