# Generated by Django 5.0.6 on 2024-05-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
            ],
        ),
        migrations.CreateModel(
            name='DayNightshift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifttype', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Day-OT', 'Day-OT'), ('Night-OT', 'Night-OT')], max_length=50, verbose_name='Shift Details')),
            ],
        ),
        migrations.CreateModel(
            name='FilmRollType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolltype', models.CharField(choices=[('Full(1)', 1), ('Half(1/2)', 0.5), ('QUATER(1/4)', 0.25), ('THREE-FOURTH(3/4)', 0.75)], max_length=50, verbose_name='Roll type')),
            ],
        ),
        migrations.CreateModel(
            name='MainTankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintankname', models.CharField(max_length=50, verbose_name='Main Tank Name')),
                ('oilname', models.CharField(max_length=50, verbose_name='Oil Name')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('capacity', models.IntegerField(verbose_name='Tank Capacity in MT')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='PackingMachineDetails',
            fields=[
                ('machineid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Machine ID')),
                ('machinename', models.CharField(max_length=50, verbose_name='Machine Name')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='PackingManagerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managername', models.CharField(max_length=50, verbose_name='Packing Manager Name')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='PackingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionname', models.CharField(max_length=50, verbose_name='Pouch Section Name')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='QCNameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qcname', models.CharField(max_length=50, verbose_name='Pouch Section Name')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='SubTankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtankname', models.CharField(max_length=50, verbose_name='Main Tank Name')),
                ('oilname', models.CharField(max_length=50, verbose_name='Oil Name')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('capacity', models.IntegerField(verbose_name='Tank Capacity in MT')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='TBHQDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(verbose_name='Measure in Grams')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='TMPSDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(verbose_name='Measure in ml')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='VitaminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitaminname', models.CharField(max_length=50, verbose_name='Vitamin Name')),
                ('units', models.IntegerField(verbose_name='Measure in Grams')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='oilcategorydetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('oilcategoryname', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.branddetails')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorNameDetails',
            fields=[
                ('empid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('operatorname', models.CharField(max_length=50, verbose_name='Operator Name')),
                ('mobileno', models.IntegerField(verbose_name='Mobile No')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('sectionname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.packingsection')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingRollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_no', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('operatorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.operatornamedetails')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.daynightshift')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingRollDetail',
            fields=[
                ('filmrollno', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Film Roll No')),
                ('filmrolldate', models.DateField(verbose_name='Film Roll Date')),
                ('grosswt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Gross Weight')),
                ('netwt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Net Weight')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('printingrollbatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.printingrollbatch')),
            ],
        ),
        migrations.CreateModel(
            name='skunamedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuname', models.CharField(max_length=50, verbose_name='SKU Name')),
                ('skucode_m', models.CharField(max_length=50, unique=True, verbose_name='SKU Code Master')),
                ('skucode_c', models.CharField(max_length=50, verbose_name='SKU Code By Category')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.oilcategorydetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRollDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runningdate', models.DateField()),
                ('runningrollstarttime', models.DateTimeField(verbose_name='Roll Start Time')),
                ('runningrollstoptime', models.DateTimeField(verbose_name='Roll Stop Time')),
                ('runningbatchno', models.CharField(max_length=50, verbose_name='Roll Batch No')),
                ('runningmrp', models.CharField(max_length=50, verbose_name='Roll MRP')),
                ('runningrollno', models.CharField(max_length=50, verbose_name='Roll No')),
                ('runningpouchcount', models.IntegerField(blank=True, null=True, verbose_name='Pouch Count')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('runningmachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.packingmachinedetails')),
                ('runningoperatorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.operatornamedetails')),
                ('runningrolltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.filmrolltype')),
                ('runningshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.daynightshift')),
                ('runningskuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.skunamedetails')),
            ],
        ),
        migrations.AddField(
            model_name='printingrollbatch',
            name='skuname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.skunamedetails'),
        ),
        migrations.CreateModel(
            name='OilPumpingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorontime', models.DateTimeField(verbose_name='Motor ON Time')),
                ('motorofftime', models.DateTimeField(verbose_name='Motor OFF Time')),
                ('maintank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.maintankdetails')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.daynightshift')),
                ('operatorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.operatornamedetails')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.packingmanagerdetails')),
                ('qcname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.qcnamedetails')),
                ('subtank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.subtankdetails')),
                ('tbhqunits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.tbhqdetails')),
                ('tmpsunits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.tmpsdetails')),
                ('vitaminunits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.vitamindetails')),
            ],
        ),
    ]
