# Generated by Django 5.0.6 on 2024-05-29 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='isdelete',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_afnoonstarttime',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_championname',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_mornstarttime',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_name',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_operatorname',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_plan',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_pouchcount',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_runningsku',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_status',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine1_wtcheckername',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_afnoonstarttime',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_championname',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_mornstarttime',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_name',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_operatorname',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_plan',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_pouchcount',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_runningsku',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_status',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine2_wtcheckername',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine_good',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine_minus',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine_plus',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine_special',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machine_stockbox',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='updatedat',
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK10 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_10_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK10 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_10_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_10_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_plan',
            field=models.IntegerField(default=1, verbose_name='IPK10 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK10 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_10_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK10 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk10_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_10_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK11 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_11_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK11 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_11_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_11_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_plan',
            field=models.IntegerField(default=1, verbose_name='IPK11 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK11 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_11_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK11 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk11_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_11_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK1 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_1_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK1 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IPK_1_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_1_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_plan',
            field=models.IntegerField(default=1, verbose_name='IPK1 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK1 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_1_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK1 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk1_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_1_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK2 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_2_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK2 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_2_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_2_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_plan',
            field=models.IntegerField(default=1, verbose_name='IPK2 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK2 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_2_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK2 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk2_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_2_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK3 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_3_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK3 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IPK_3_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_3_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_plan',
            field=models.IntegerField(default=1, verbose_name='IPK3 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK3 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_3_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK3 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk3_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_3_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK4 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_4_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK4 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_4_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_4_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_plan',
            field=models.IntegerField(default=1, verbose_name='IPK4 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK4 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_4_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK4 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk4_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_4_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK5 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_5_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK5 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IPK_5_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_5_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_plan',
            field=models.IntegerField(default=1, verbose_name='IPK5 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK5 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_5_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK5 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk5_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_5_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK6 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_6_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK6 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_6_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_6_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_plan',
            field=models.IntegerField(default=1, verbose_name='IPK6 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK6 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_6_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK6 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk6_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_6_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK7 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_7_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK7 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IPK_7_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_7_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_plan',
            field=models.IntegerField(default=1, verbose_name='IPK6 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK7 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_7_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK7 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk7_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_7_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK8 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_8_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK8 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_8_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_8_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_plan',
            field=models.IntegerField(default=1, verbose_name='IPK8 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK6 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_8_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK8 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk8_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_8_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK9 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_9_championname', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='IPK9 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IPK_9_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_9_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_plan',
            field=models.IntegerField(default=1, verbose_name='IPK9 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_pouchcount',
            field=models.IntegerField(default=1, verbose_name='IPK9 Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_9_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK9 ON or OFF Status'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='ipk9_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_9_wtcheckername', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='shiftoverallplan',
            field=models.IntegerField(default=1, verbose_name='Dayshift Overall Machine Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine1_good',
            field=models.IntegerField(default=1, verbose_name='Machine1 Good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine1_minus',
            field=models.IntegerField(default=1, verbose_name='Machine1 Minus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine1_plus',
            field=models.IntegerField(default=1, verbose_name='Machine1 Plus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine1_special',
            field=models.IntegerField(default=1, verbose_name='Machine1 Special'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine1_stockbox',
            field=models.IntegerField(default=1, verbose_name='Machine1 Complaint Stock Box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine2_good',
            field=models.IntegerField(default=1, verbose_name='Machine2 Good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine2_minus',
            field=models.IntegerField(default=1, verbose_name='Machine2 Minus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine2_plus',
            field=models.IntegerField(default=1, verbose_name='Machine2 Plus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine2_special',
            field=models.IntegerField(default=1, verbose_name='Machine2 Special'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine2_stockbox',
            field=models.IntegerField(default=1, verbose_name='Machine2 Complaint Stock Box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine3_good',
            field=models.IntegerField(default=1, verbose_name='Machine3 Good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine3_minus',
            field=models.IntegerField(default=1, verbose_name='Machine3 Minus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine3_plus',
            field=models.IntegerField(default=1, verbose_name='Machine3 Plus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine3_special',
            field=models.IntegerField(default=1, verbose_name='Machine3 Special'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine3_stockbox',
            field=models.IntegerField(default=1, verbose_name='Machine3 Complaint Stock Box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine4_good',
            field=models.IntegerField(default=1, verbose_name='Machine4 Good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine4_minus',
            field=models.IntegerField(default=1, verbose_name='Machine4 Minus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine4_plus',
            field=models.IntegerField(default=1, verbose_name='Machine4 Plus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine4_special',
            field=models.IntegerField(default=1, verbose_name='Machine4 Special'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='wtmachine4_stockbox',
            field=models.IntegerField(default=1, verbose_name='Machine4 Complaint Stock Box'),
            preserve_default=False,
        ),
    ]
