# Generated by Django 5.0.6 on 2024-05-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skunamedetails',
            name='isdelete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
