# Generated by Django 5.0.6 on 2024-05-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilpumpingdetails',
            name='vitaminunits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Packing.vitamindetails'),
        ),
    ]
