# Generated by Django 5.0.6 on 2024-06-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0002_srdailystockdetails_stockmode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='srdailystockdetails',
            name='updatedby',
            field=models.CharField(default='admin', max_length=50, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='skunamedetails',
            name='skutype',
            field=models.CharField(choices=[('PET', 'PET'), ('JAR', 'JAR'), ('POUCH', 'POUCH')], default='POUCH', max_length=50, verbose_name='SKU Type'),
        ),
    ]
