# Generated by Django 5.0.6 on 2024-05-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0002_remove_ppsrdetails_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk1_runningsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_1_runningsku', to='Packing.skunamedetails'),
        ),
    ]
