# Generated by Django 5.0.6 on 2024-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0002_skunamedetails_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingrolldetail',
            name='grosswt',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Gross Weight'),
        ),
        migrations.AlterField(
            model_name='printingrolldetail',
            name='netwt',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Net Weight'),
        ),
    ]
