# Generated by Django 5.0.6 on 2024-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0003_srdailystockdetails_updatedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srdailystockdetails',
            name='updatedby',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Updated By'),
        ),
    ]
