# Generated by Django 5.0.6 on 2024-05-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0004_alter_ppsrdetails_ipk10_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk10_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ipk_10_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk10_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK10 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk1_operatorname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_1_operatorname', to='Packing.operatornamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk1_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK1 Plan'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk1_pouchcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK1 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk2_operatorname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_2_operatorname', to='Packing.operatornamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk2_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK2 Plan'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk2_pouchcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK2 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk2_runningsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_2_runningsku', to='Packing.skunamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk2_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK2 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk3_operatorname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_3_operatorname', to='Packing.operatornamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk3_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK3 Plan'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk3_pouchcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK3 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk3_runningsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_3_runningsku', to='Packing.skunamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk3_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK3 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk4_operatorname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_4_operatorname', to='Packing.operatornamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk4_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK4 Plan'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk4_pouchcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK4 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk4_runningsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_4_runningsku', to='Packing.skunamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk4_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK4 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk5_operatorname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_5_operatorname', to='Packing.operatornamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk5_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK5 Plan'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk5_pouchcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK5 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk5_runningsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_5_runningsku', to='Packing.skunamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk5_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK5 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk6_operatorname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_6_operatorname', to='Packing.operatornamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk6_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK6 Plan'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk6_pouchcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK6 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk6_runningsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_6_runningsku', to='Packing.skunamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk6_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK6 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk7_operatorname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_7_operatorname', to='Packing.operatornamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk7_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK6 Plan'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk7_pouchcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK7 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk7_runningsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_7_runningsku', to='Packing.skunamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk7_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK7 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk8_operatorname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_8_operatorname', to='Packing.operatornamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk8_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK8 Plan'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk8_pouchcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPK6 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk8_runningsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipk_8_runningsku', to='Packing.skunamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk8_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK8 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk9_name',
            field=models.ForeignKey(default='IPK9', on_delete=django.db.models.deletion.CASCADE, related_name='IPK_9_machinename', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='ipk9_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=50, verbose_name='IPK9 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine1_good',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine1 Good'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine1_minus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine1 Minus'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine1_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine1 Plus'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine1_special',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine1 Special'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine1_stockbox',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine1 Complaint Stock Box'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine2_good',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine2 Good'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine2_minus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine2 Minus'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine2_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine2 Plus'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine2_special',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine2 Special'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine2_stockbox',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine2 Complaint Stock Box'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine3_good',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine3 Good'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine3_minus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine3 Minus'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine3_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine3 Plus'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine3_special',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine3 Special'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine3_stockbox',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine3 Complaint Stock Box'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine4_good',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine4 Good'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine4_minus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine4 Minus'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine4_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine4 Plus'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine4_special',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine4 Special'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='wtmachine4_stockbox',
            field=models.IntegerField(blank=True, null=True, verbose_name='Machine4 Complaint Stock Box'),
        ),
    ]
