# Generated by Django 5.0.6 on 2024-05-23 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0004_printingrollbatch_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRollType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolltype', models.CharField(choices=[('Full(1)', 1), ('Half(1/2)', 0.5), ('QUATER(1/4)', 0.25), ('THREE-FOURTH(3/4)', 0.75)], max_length=50, verbose_name='Roll type')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorNameDetails',
            fields=[
                ('empid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('operatorname', models.CharField(max_length=50, verbose_name='Operator Name')),
                ('mobileno', models.IntegerField(verbose_name='Mobile No')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='PackingMachineDetails',
            fields=[
                ('machineid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Machine ID')),
                ('machinename', models.CharField(max_length=50, verbose_name='Machine Name')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRollDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runningdate', models.DateField()),
                ('runningrollstarttime', models.DateTimeField(auto_now_add=True, verbose_name='Roll Start Time')),
                ('runningrollstoptime', models.DateTimeField(auto_now_add=True, verbose_name='Roll Stop Time')),
                ('runningbatchno', models.CharField(max_length=50, verbose_name='Roll Batch No')),
                ('runningmrp', models.CharField(max_length=50, verbose_name='Roll MRP')),
                ('runningrollno', models.CharField(max_length=50, verbose_name='Roll No')),
                ('runningmachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.packingmachinedetails')),
                ('runningoperatorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.operatornamedetails')),
                ('runningrolltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.filmrolltype')),
                ('runningshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.daynightshift')),
                ('runningskuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.skunamedetails')),
            ],
        ),
    ]
