# Generated by Django 5.0.6 on 2024-05-25 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0004_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPouchCuttingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Entry Date')),
                ('sfleakinmt', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='SF Leak in MT')),
                ('gnleakinmt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='SF Leak in MT')),
                ('gnrleakinmt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='SF Leak in MT')),
                ('rbleakinmt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='SF Leak in MT')),
                ('palmleakinmt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='SF Leak in MT')),
                ('ginleakinmt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='SF Leak in MT')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='Remarks')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('operatorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.operatornamedetails')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.daynightshift')),
            ],
        ),
    ]
