# Generated by Django 5.0.6 on 2024-06-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0004_alter_srdailystockdetails_updatedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='srdailystockdetails',
            name='godownname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Packing.godowndetails'),
        ),
        migrations.AlterField(
            model_name='skunamedetails',
            name='skutype',
            field=models.CharField(choices=[('POUCH', 'POUCH'), ('JAR', 'JAR'), ('PET', 'PET')], default='POUCH', max_length=50, verbose_name='SKU Type'),
        ),
    ]
