# Generated by Django 5.0.6 on 2024-05-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0005_filmrolltype_operatornamedetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrolldetails',
            name='runningpouchcount',
            field=models.IntegerField(default=0, verbose_name='Pouch Count'),
            preserve_default=False,
        ),
    ]
