# Generated by Django 5.0.6 on 2024-05-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0005_dailypouchcuttingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualLeakChangeManpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindimanpower', models.IntegerField(verbose_name='Total Hindi Manpower')),
                ('ladiesmanpower', models.IntegerField(verbose_name='Total Ladies Manpower')),
                ('date', models.DateField(verbose_name='Leak Change Date')),
                ('changeddamagebox', models.IntegerField(verbose_name='Total Leak Change Box')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='PouchLeakMistakesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistakename', models.CharField(max_length=50, verbose_name='Name of Mistake')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='ManualLeakChangeBatchDetailsFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchno', models.IntegerField(verbose_name='Batch No')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.daynightshift')),
                ('skuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.skunamedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ManualLeakChangeRollPouchFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofpouch', models.IntegerField(verbose_name='No of Leak Pouch')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('batchno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.manualleakchangebatchdetailsfs')),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.printingrolldetail')),
                ('mistakename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.pouchleakmistakesname')),
            ],
        ),
    ]
