# Generated by Django 5.0.6 on 2024-05-25 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0006_manualleakchangemanpower_pouchleakmistakesname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualleakchangebatchdetailsfs',
            name='manpowerdetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Packing.manualleakchangemanpower'),
            preserve_default=False,
        ),
    ]
