# Generated by Django 5.0.6 on 2024-05-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0006_productionrolldetails_runningpouchcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrolldetails',
            name='runningpouchcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pouch Count'),
        ),
    ]
