# Generated by Django 5.0.6 on 2024-05-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0007_alter_productionrolldetails_runningpouchcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrolldetails',
            name='isdelete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='productionrolldetails',
            name='updatedat',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated AT'),
        ),
    ]
