# Generated by Django 5.0.6 on 2024-05-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0007_manualleakchangebatchdetailsfs_manpowerdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualleakchangerollpouchfs',
            name='batchno',
        ),
        migrations.AddField(
            model_name='manualleakchangemanpower',
            name='shift',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Packing.daynightshift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualleakchangerollpouchfs',
            name='manpower',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Packing.manualleakchangemanpower'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ManualLeakChangeBatchDetailsFS',
        ),
    ]
