# Generated by Django 5.0.6 on 2024-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0007_alter_skunamedetails_skutype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skunamedetails',
            name='skutype',
            field=models.CharField(choices=[('PET', 'PET'), ('POUCH', 'POUCH'), ('JAR', 'JAR')], default='POUCH', max_length=50, verbose_name='SKU Type'),
        ),
    ]
