# Generated by Django 5.0.6 on 2024-05-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0008_remove_manualleakchangerollpouchfs_batchno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilpumpingdetails',
            name='date',
            field=models.DateField(default='2020-01-01', verbose_name='Date'),
            preserve_default=False,
        ),
    ]
