# Generated by Django 5.0.6 on 2024-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0008_productionrolldetails_isdelete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrolldetails',
            name='runningrollstarttime',
            field=models.DateTimeField(verbose_name='Roll Start Time'),
        ),
        migrations.AlterField(
            model_name='productionrolldetails',
            name='runningrollstoptime',
            field=models.DateTimeField(verbose_name='Roll Stop Time'),
        ),
    ]
