# Generated by Django 5.0.6 on 2024-05-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0009_alter_productionrolldetails_runningrollstarttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingrollbatch',
            name='operator_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.operatornamedetails'),
        ),
    ]
