# Generated by Django 5.0.6 on 2024-05-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0009_oilpumpingdetails_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPSRDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='PPSR Date')),
                ('expbox', models.IntegerField(verbose_name='Expected Box')),
                ('actbox', models.IntegerField(verbose_name='Actual Box')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='Remarks')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
    ]
