# Generated by Django 5.0.6 on 2024-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0010_ppsrdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppsrdetails',
            name='date',
            field=models.DateField(unique=True, verbose_name='PPSR Date'),
        ),
    ]
