# Generated by Django 5.0.6 on 2024-05-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0010_alter_printingrollbatch_operator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingrollbatch',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Packing.operatornamedetails'),
        ),
    ]
