# Generated by Django 5.0.6 on 2024-05-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0011_alter_ppsrdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrolldetails',
            name='runningmrp',
            field=models.IntegerField(verbose_name='MRP'),
        ),
    ]
