# Generated by Django 5.0.6 on 2024-05-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0012_printingoperatornamedetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingrollbatch',
            name='operatorname',
        ),
        migrations.AddField(
            model_name='printingrollbatch',
            name='operator_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrintingOperatorNameDetails',
        ),
    ]
