# Generated by Django 5.0.6 on 2024-07-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Packing", "0012_alter_skunamedetails_skutype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skunamedetails",
            name="skutype",
            field=models.CharField(
                choices=[("JAR", "JAR"), ("PET", "PET"), ("POUCH", "POUCH")],
                default="POUCH",
                max_length=50,
                verbose_name="SKU Type",
            ),
        ),
        migrations.CreateModel(
            name="CSMillskulist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updatedat",
                    models.DateTimeField(auto_now=True, verbose_name="Updated AT"),
                ),
                (
                    "isdelete",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "csskuname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Packing.skunamedetails",
                    ),
                ),
            ],
        ),
    ]
