# Generated by Django 5.0.6 on 2024-05-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0012_alter_productionrolldetails_runningmrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOpendingClosingStockDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('skucode', models.CharField(max_length=50, verbose_name='SKUCODE')),
                ('categoryname', models.CharField(max_length=50, verbose_name='Category Name')),
                ('skuname', models.CharField(max_length=50, verbose_name='SKU Name')),
                ('openingstock', models.IntegerField(verbose_name='Opening Stock')),
                ('sales', models.IntegerField(verbose_name='Sales')),
                ('closingstock', models.IntegerField(verbose_name='Closing Stock')),
                ('production', models.IntegerField(verbose_name='Productin')),
                ('noofemptycottonbox', models.IntegerField(verbose_name='No of Empty Cotton Box')),
            ],
        ),
    ]
