# Generated by Django 5.0.6 on 2024-05-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0013_dispatchopendingclosingstockdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchopendingclosingstockdetails',
            name='noofemptycottonbox',
            field=models.IntegerField(blank=True, null=True, verbose_name='No of Empty Cotton Box'),
        ),
    ]
