# Generated by Django 5.0.6 on 2024-05-28 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0014_alter_dispatchopendingclosingstockdetails_noofemptycottonbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchopendingclosingstockdetails',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchopendingclosingstockdetails',
            name='isdelete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='dispatchopendingclosingstockdetails',
            name='updatedat',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated AT'),
        ),
    ]
