# Generated by Django 5.0.6 on 2024-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0014_alter_skunamedetails_skutype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skunamedetails',
            name='skutype',
            field=models.CharField(choices=[('JAR', 'JAR'), ('POUCH', 'POUCH'), ('PET', 'PET')], default='POUCH', max_length=50, verbose_name='SKU Type'),
        ),
    ]
