# Generated by Django 5.0.6 on 2024-05-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0015_dispatchopendingclosingstockdetails_createdat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PPSRDetails',
            new_name='ExpVsActDetails',
        ),
    ]
