# Generated by Django 5.0.6 on 2024-05-28 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0016_rename_ppsrdetails_expvsactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionNameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractorname', models.CharField(max_length=50, verbose_name='Contractor Name')),
                ('championname', models.CharField(max_length=50, unique=True, verbose_name='Champion Name')),
                ('wtchecker', models.CharField(max_length=50, verbose_name='Weight Checker Name')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.AlterField(
            model_name='filmrolltype',
            name='rolltype',
            field=models.CharField(choices=[('FULL(1)', 1), ('HALF(1/2)', 0.5), ('QUATOR(1/4)', 0.25), ('THREE-FOURTH(3/4)', 0.75)], max_length=50, verbose_name='Roll type'),
        ),
        migrations.AddField(
            model_name='productionrolldetails',
            name='championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Packing.championnamedetails'),
        ),
        migrations.CreateModel(
            name='PPSRDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Entry Date&Time')),
                ('overallproductionplan', models.IntegerField(verbose_name='Over All Plan')),
                ('machinename_status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=50, verbose_name='Machine1 ON or OFF Status')),
                ('machinename_plus', models.IntegerField(verbose_name='Machine Plus')),
                ('machinename_good', models.IntegerField(verbose_name='Machine Good')),
                ('machinename_minus', models.IntegerField(verbose_name='Machine Minus')),
                ('machinename_special', models.IntegerField(verbose_name='Machine Special')),
                ('machinename_stockbox', models.IntegerField(verbose_name='Machine Complaint Stock Box')),
                ('machinename_pouchcount', models.IntegerField(verbose_name='Pouch Count')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated AT')),
                ('isdelete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('machinename_championname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championname_details', to='Packing.championnamedetails')),
                ('machinename_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.packingmachinedetails')),
                ('machinename_operatorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.operatornamedetails')),
                ('machinename_runningsku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packing.skunamedetails')),
                ('machinename_wtcheckername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wtcheckername_details', to='Packing.championnamedetails')),
            ],
        ),
    ]
