# Generated by Django 5.0.6 on 2024-05-28 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0017_championnamedetails_alter_filmrolltype_rolltype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppsrdetails',
            name='machinename_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='championname_details', to='Packing.championnamedetails'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='machinename_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wtcheckername_details', to='Packing.championnamedetails'),
        ),
    ]
