# Generated by Django 5.0.6 on 2024-05-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0018_alter_ppsrdetails_machinename_championname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packingmachinedetails',
            old_name='machinename',
            new_name='machine1',
        ),
        migrations.RenameField(
            model_name='ppsrdetails',
            old_name='machinename_pouchcount',
            new_name='machine1_pouchcount',
        ),
        migrations.RenameField(
            model_name='ppsrdetails',
            old_name='machinename_good',
            new_name='machine_good',
        ),
        migrations.RenameField(
            model_name='ppsrdetails',
            old_name='machinename_minus',
            new_name='machine_minus',
        ),
        migrations.RenameField(
            model_name='ppsrdetails',
            old_name='machinename_plus',
            new_name='machine_plus',
        ),
        migrations.RenameField(
            model_name='ppsrdetails',
            old_name='machinename_special',
            new_name='machine_special',
        ),
        migrations.RenameField(
            model_name='ppsrdetails',
            old_name='machinename_stockbox',
            new_name='machine_stockbox',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machinename_championname',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machinename_name',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machinename_operatorname',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machinename_runningsku',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machinename_status',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='machinename_wtcheckername',
        ),
        migrations.RemoveField(
            model_name='ppsrdetails',
            name='overallproductionplan',
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine1_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='Machine1 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine1_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='championname1_details', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine1_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='Machine1 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine1_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machine1_name', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine1_operatorname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='machine1_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine1_plan',
            field=models.IntegerField(default=1, verbose_name='Machine1 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine1_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machine1_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine1_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default=1, max_length=50, verbose_name='Machine1 ON or OFF Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine1_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wtcheckername1_details', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_afnoonstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='Machine1 Afternoon start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_championname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='championname2_details', to='Packing.championnamedetails'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_mornstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='Machine1 Morning start Time'),
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machine2_name', to='Packing.packingmachinedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_operatorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machine2_operatorname', to='Packing.operatornamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_plan',
            field=models.IntegerField(default=1, verbose_name='Machine1 Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_pouchcount',
            field=models.IntegerField(default=1, verbose_name='Pouch Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_runningsku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machine2_runningsku', to='Packing.skunamedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default=1, max_length=50, verbose_name='Machine1 ON or OFF Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppsrdetails',
            name='machine2_wtcheckername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wtcheckername2_details', to='Packing.championnamedetails'),
        ),
    ]
