# Generated by Django 5.0.6 on 2024-05-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0019_rename_machinename_packingmachinedetails_machine1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packingmachinedetails',
            old_name='machine1',
            new_name='machine',
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='machine1_pouchcount',
            field=models.IntegerField(verbose_name='Machine1 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='machine1_status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=50, verbose_name='Machine1 ON or OFF Status'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='machine2_plan',
            field=models.IntegerField(verbose_name='Machine2 Plan'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='machine2_pouchcount',
            field=models.IntegerField(verbose_name='Machine2 Pouch Count'),
        ),
        migrations.AlterField(
            model_name='ppsrdetails',
            name='machine2_status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=50, verbose_name='Machine1 ON or OFF Status'),
        ),
    ]
