# Generated by Django 5.0.6 on 2024-06-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Plant_I', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Pack_dailystock_access',
            field=models.CharField(default=False, max_length=50, verbose_name='Pack-DailyStock'),
        ),
    ]
