# Generated by Django 5.0.6 on 2024-05-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Plant_I', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='app1_access',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='app2_access',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='app3_access',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='app4_access',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='app5_access',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Pack_dashboard_access',
            field=models.BooleanField(default=False, verbose_name='Pack_MainDashboard'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Pack_expvsact_access',
            field=models.BooleanField(default=False, verbose_name='Pack_ExpVsAct'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Pack_manualleakchange_access',
            field=models.BooleanField(default=False, verbose_name='Pack_ManualLeakChange'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Pack_oilpump_access',
            field=models.BooleanField(default=False, verbose_name='Pack_OilPump'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Pack_pouchcutting_access',
            field=models.BooleanField(default=False, verbose_name='Pack_PouchCutting'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Pack_printing_access',
            field=models.BooleanField(default=False, verbose_name='Pack_Printing'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Pack_production_access',
            field=models.BooleanField(default=False, verbose_name='Pack_Production'),
        ),
    ]
