# Generated by Django 5.0.6 on 2024-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Plant_I', '0002_customuser_pack_dailystock_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Pack_dailystock_access',
            field=models.BooleanField(default=False, verbose_name='Pack_DailyStock'),
        ),
    ]
